version: "2"         # required to adjust maintainability checks
exclude_patterns:
  - "chalice/"
  - "checksumming_io/"
  - "config/"
  - "daemons/"
  - "scripts/"
  - "tests/"
  - "uploadctl/"
  - "venv/"
