language: python
cache:
  pip: true
  directories:
  - ".chalice/venv"
python:
- 3.6
dist: trusty
addons:
  apt:
    packages:
    - jq
    - moreutils
    - gettext
install:
- pip install -r requirements.txt
- pip install -r requirements-dev.txt
script:
- source config/environment
- make test
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  provider: script
  script: make deploy
  skip_cleanup: true
  on:
    branch: master
    python: 3.6
env:
  global:
  - DEPLOYMENT_STAGE=test
  - secure: VgZRcYV3jSpel8nicD1Pr9QpbeYQcD1fUjct6g2Ke0YGnLRXmiFffAjgSH71UK1eddN9PT8K0LLfSD0+rr/Dl1o9TdMi2XFWNuBGhr8ger/oRUQuy1HAZQ5ivhzqZqIaCZ4v+DdK/OXGjf36IgPGoZmtAUXfv6HzQ0+276kUTHFaqXCyApn1+5Ni2dhzCQF4JnbAarvpMTdS7harcfkL4ALNsgXDxSeIuYa/N6jkCTQbECYR+168jbGKnIyrPVAplOm7gI+tGrgKhTd3S3PEJR1H9QH31C1/iI9eOiSe71yVDyBWcdDBQHIbn5Ig1bi/9XAc/3vCk0nhDskQ0sLvvsmyK+q8cFCYxmXexcqioPjG6e48mv/Hr/xZMrGPDpr0IGShmpa8ZqMWH/KUfD0MGGAFvSwZU8nR3xoMSem/Ewnm1On8uFb2WyESTgwcUPVKUd4JkTyS+ZbDv2c2/F46ZbwQIkMA6zRThubtZdzzNzTMTY2IvY/anFdxzGp2g0sn6n3/4Vg34lTiIzQePiYeVb0OAEMeOHa0xFislQS8bVU42QRwCaQ+43/VGlhsaJO1/sEoga5rkRVgld58ZrVwYNHBR1fWfa8uOn6d1VWtCUP95pneNvEPe8kBCqW8CMgW/Riiio0fujnnTaXPA42TPchbKFtPEULe8265T7dP5zw=
  - secure: pyrI2UGM22pbBwbA+HrGyF1IMtU6H2tYmrZ+udZCIBGloGz+qtyjgLpJgFRwoTeksdfPFl4XDckEkQGILkKE6gnkBOBhL59qHdcJDV3T8kH5pBMxpKgUzSo3Tu7mjR8GxJOYK+sZa9oM8T8eMC87RdUdpjWRJB/XfJfQpPO1WE6FJNbQzaQvpolhA45DbrFXeLu7oiMAuCI3sY5c8esKPtUtbNtVuVfIY6NwXGdCYonEHOSsaQE7eYnKSMOMts/5pnw74QXVJHJYF7j6AkzXme49q3zjjtA/MEW2kuMSUfK+pSgv0EJD02V60+QWHFlNvHdjfMDQF5Vi4hI8Kqo3I0TQkErHA/gbtYEEjEjC0qF5rrvGnMcRlvbYlS/7Vks9iPrBXOiDbaLt5CpvS8cu0GKJ1G7UPY69iCFIoPD7hrYzZwZQeix69ZvNhT/WFOoNGm0u4x4lTROQJHyakej06P7jEmaYkA1Cu4vHzO/u+TAljHnSXTggJCizG4dgY19KLEo4zzsUha8dWm3H75dIpCYNoKLmwCaKqZWsdBdrmL+eRDITf8QDIuLUnFxp4nsIagGG8fJX9szaqwDkb9/xhPSDA255jnY+FPdJ63MGa5vmt2d84M5u0VdbdOEnhZjJvsHZdLeAlB0TJkHq06wWG+lS5/zc3wd4xaBBLz41Gvo=
