language: python
cache:
  pip: true
  directories:
    - ".chalice/venv"
python:
  - 3.6
dist: trusty
addons:
  apt:
    packages:
      - jq
      - moreutils
      - gettext
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip list
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - source config/environment
  - make test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
after_success:
  - bash <(curl -s https://codecov.io/bash)
deploy:
  # deploy master branch to the dev environment
  - provider: script
    script: scripts/deploy.sh dev
    skip_cleanup: true
    on:
      branch: master
      python: 3.6
  # deploy integration branch to the integration environment
  - provider: script
    script: scripts/deploy.sh integration
    skip_cleanup: true
    on:
      branch: integration
      python: 3.6
  # deploy staging branch to staging environment
  - provider: script
    script: scripts/deploy.sh staging
    skip_cleanup: true
    on:
      branch: staging
      python: 3.6
env:
  global:
    - CC_TEST_REPORTER_ID=8673a342bc2822cbdfe151982a7e72743f44fecd030867754d8d34ebf845b130
    # AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY
    - secure: VgZRcYV3jSpel8nicD1Pr9QpbeYQcD1fUjct6g2Ke0YGnLRXmiFffAjgSH71UK1eddN9PT8K0LLfSD0+rr/Dl1o9TdMi2XFWNuBGhr8ger/oRUQuy1HAZQ5ivhzqZqIaCZ4v+DdK/OXGjf36IgPGoZmtAUXfv6HzQ0+276kUTHFaqXCyApn1+5Ni2dhzCQF4JnbAarvpMTdS7harcfkL4ALNsgXDxSeIuYa/N6jkCTQbECYR+168jbGKnIyrPVAplOm7gI+tGrgKhTd3S3PEJR1H9QH31C1/iI9eOiSe71yVDyBWcdDBQHIbn5Ig1bi/9XAc/3vCk0nhDskQ0sLvvsmyK+q8cFCYxmXexcqioPjG6e48mv/Hr/xZMrGPDpr0IGShmpa8ZqMWH/KUfD0MGGAFvSwZU8nR3xoMSem/Ewnm1On8uFb2WyESTgwcUPVKUd4JkTyS+ZbDv2c2/F46ZbwQIkMA6zRThubtZdzzNzTMTY2IvY/anFdxzGp2g0sn6n3/4Vg34lTiIzQePiYeVb0OAEMeOHa0xFislQS8bVU42QRwCaQ+43/VGlhsaJO1/sEoga5rkRVgld58ZrVwYNHBR1fWfa8uOn6d1VWtCUP95pneNvEPe8kBCqW8CMgW/Riiio0fujnnTaXPA42TPchbKFtPEULe8265T7dP5zw=
    - secure: pyrI2UGM22pbBwbA+HrGyF1IMtU6H2tYmrZ+udZCIBGloGz+qtyjgLpJgFRwoTeksdfPFl4XDckEkQGILkKE6gnkBOBhL59qHdcJDV3T8kH5pBMxpKgUzSo3Tu7mjR8GxJOYK+sZa9oM8T8eMC87RdUdpjWRJB/XfJfQpPO1WE6FJNbQzaQvpolhA45DbrFXeLu7oiMAuCI3sY5c8esKPtUtbNtVuVfIY6NwXGdCYonEHOSsaQE7eYnKSMOMts/5pnw74QXVJHJYF7j6AkzXme49q3zjjtA/MEW2kuMSUfK+pSgv0EJD02V60+QWHFlNvHdjfMDQF5Vi4hI8Kqo3I0TQkErHA/gbtYEEjEjC0qF5rrvGnMcRlvbYlS/7Vks9iPrBXOiDbaLt5CpvS8cu0GKJ1G7UPY69iCFIoPD7hrYzZwZQeix69ZvNhT/WFOoNGm0u4x4lTROQJHyakej06P7jEmaYkA1Cu4vHzO/u+TAljHnSXTggJCizG4dgY19KLEo4zzsUha8dWm3H75dIpCYNoKLmwCaKqZWsdBdrmL+eRDITf8QDIuLUnFxp4nsIagGG8fJX9szaqwDkb9/xhPSDA255jnY+FPdJ63MGa5vmt2d84M5u0VdbdOEnhZjJvsHZdLeAlB0TJkHq06wWG+lS5/zc3wd4xaBBLz41Gvo=
    # enc_password
    - secure: AIB4I+rWirx+fIheq0lHno8JFhWSmjg5p+/CyIK9FoD2WBb18vPaEMkuDxblUox9sUDjVAaxFNs1iTIOdxchflA9oW5LQttJKJWdjlMKW1tdJ9ipUdxZ6qnCP84OEL8fJMT4rvrzA17DTOWzXCDoJzNyab6O6TXb3WGYf57OyAkGdZ6GUJmeQmSbLmXLRYpWru0uam8Q9gtIHuFH151sOWWWNLTLFM8idxp4LIWVO1u8vADIhxd9i1HkOj4lYrrNTsHAcilVR1yMj3ovaJOTDNk1D6067ZI3rzb3lUOqZIIz1loNUwz6zqp8isAZ1Dnzz/+I5Q9uKoYIrnYX245L8I6vU71EiSTbgsHwdLn5ICLpyrBDr7YVBg68lrqzEzQWKWkBC0jeGGjCwdZitb+o4MmlG3f7W9g5a/OLelTdiDcgM+3nj2QgApGnAZle7kJW90jEC3aroNbSuHnffX6tmwdil4m5eyqqAWwwOQ3OpVR4yM4vxeaL5xnCVwJ4N3ZYTzvDlaUURqoqKOsCVlGBETS3XdOqg17MFBk+H5GsATOno1rMHo7ztBIvcqzyIj4RvxFTFrMehFnJ9lLUlpo7R0I3chXNzijLWbrkKcFJB7+Ujo/bTBH5VsvShjpAkAWlKx63Js97+bN8prslA3uJ0y4He2nKvIQmrItgztreQgs=
    # GITHUB_ACCESS_TOKEN
    - secure: "da2Ip1Znt2P/jNix2s3q5HDudOUCfu2GerrDhs+rksB3UkB+SZjQg7me1Lyslw+cRRBS7FKTdpq1DYXdOoBe/zpYj2vCINu46dMOyLYuITxDJOdKfCj4L5K1pzH+cq05GvcqMP/rR774oLzjzhY2URs1nGJIkurHpVhsv9kKuCOFaouXcFcpCr59+9JXBwHnxkNBn2TfC/VdBaZ4Ks+VI9cexCWgE0ZgEVNZKImd5MBbG6v8dkQX3O1tgi6/YmWNo1YDFmsrHsgrgllB69B2Iag0gAc+a5a0OUmJXx7yRmnM1unaHygYRJ+NbK6c+hHgmsR9JGCbPlZSCGVcCy6QFFpQAXd2eacdRvctFhfJd6KtSyIl+hzk5yus3QmJsYYgQ7+IwEnsn+FdxzNCJCCqq7KW2ATkn2uAfjAfD8OkQKBtFEjgZ3maIB4DmjFf2BGTdTHsdEROrMpdGXugkEzM9cVnvsSPxRgxi4sV6Afq6/XcXhFWVZ49o+sgj1lqNLa25KpkJzGWzuQimTYV/t0QCuKjuiwG7rsyb6/INS1koFXmmpnrI2j9UPZlfZ1pynbkW+2J8K9nWvFOoH+iUqkFQcBs7AHVqH0nzgt8nHW0wNm3MqEx9deMkorwNttgBtGh5SoTKZMa94k344L/aoo4Ddw+OG9KuksbSngx+9wGMh0="
    # TERRAFORM_STATE_BUCKET
      secure: GGxcg2APMUgjtS5qYRJ6LqpbfdvAChozvYyvDKPJg8y/uuUaTzhcgJOD+HJCYHZcsaQ3c8w7uoT/07zP7yjE4+1NsvYAfMBjcMZvuzzOq5nzo6fIK3+DludYnPW2NrcuMBS2C9pWiF5tOfD2RswY/GExWvI7f7v+EwgiiRBccbXrUcB8raGPss80uw5UxBEtlsYAqdDUZ3nLWkXgYK4RV+cUytf6C2caRNtrP9AZmF5xBNnvwp+KTW0hnmObyAuxhOzQ+CgcJcyN0+m/aE/lh9uEZhXRG1uoE0j9D8YUPLa3JXXbxQuCB9xBH1+/7nu/ld5uczFIEVeNGIw9ubUvzzpOByKulWU2hoLDVs1VHZWLiNQSXv8Gsq7Sx/5MUitVdTiPkvSJBkU1m7bYdRfOucJDPZrDwmT3FYT+4DyC+r7qr/Tvic/C/+id9cPOcie5Z0vg9UBX2XbUUgej+E9Iqce8rXR/qTedEFTNqcwTyDhy5nINVqN6TTTl5n3n7StwetE+1M6M9MDHx8ceyxkAa/2s0yQwAIux16NGblaCts3BrAQ5M04vs4AIVJvWrKoflVMLRkyYJkgp76iwXYOBw/YQuIknsmlwU5hZP71XIhz+CTUfhTBmqyYE59jcFZSr19gwFxi97R+DrrXr7Z05/0bHGzapmNGuZ3WbMQxtKWU=
