swagger: '2.0'
info:
  title: HCA DCP Staging Service API
  description: Human Cell Atlas Data Coordination Platform Staging Service API
  version: "0.0.2"
host: staging.dev.data.humancellatlas.org
schemes:
  - https
basePath: /v1
consumes:
  - application/json
  - application/octet-stream
produces:
  - application/json
paths:

  /area/{staging_area_id}:

    post:
      summary: Create a Staging Area
      operationId: staging.api.area.create
      description: |
        Create a Staging Area
      parameters:
        - name: staging_area_id
          in: path
          description: |
            A RFC4122-compliant ID for the staging area.
          required: true
          type: string
          pattern: "[A-Za-z0-9]{8}-[A-Za-z0-9]{4}-[A-Za-z0-9]{4}-[A-Za-z0-9]{4}-[A-Za-z0-9]{12}"
      responses:
        201:
          description: Staging area was created.
        409:
          description: A staging area with that ID already exists.
        default:
          description: Unexpected error

    delete:
      summary: Delete a Staging Area
      description: |
        Delete a Staging Area
      parameters:
        - name: staging_area_id
          in: path
          description: A RFC4122-compliant ID for the staging area.
          required: true
          type: string
      responses:
        204:
          description: Staging area was deleted.
        404:
          description: Could not find a staging area with that ID.
        default:
          description: Unexpected error

    get:
      summary: List files in a staging area
      operationId: staging.api.area.list_files
      description: |
        Provide a JSON object listing all the files in a staging area, including their checkums.
      parameters:
        - name: staging_area_id
          in: path
          description: A RFC4122-compliant ID for the staging area.
          required: true
          type: string
      responses:
        200:
          description: Here's your listing.
        404:
          description: Could not find a staging area with that ID.
        default:
          description: Unexpected error

  /area/{staging_area_id}/lock:

    post:
      summary: Lock a Staging Area
      operationId: staging.api.area.lock
      description: |
        Lock a Staging area so that submitters may not add/delete/rename files in it.
      parameters:
        - name: staging_area_id
          in: path
          description: A RFC4122-compliant ID for the staging area.
          required: true
          type: string
      responses:
        204:
          description: Staging area is now locked.
        default:
          description: Unexpected error

    delete:
      summary: Unock a Staging Area
      operationId: staging.api.area.unlock
      description: |
        Unlock a Staging area so that submitters may add/delete/rename files in it.
      parameters:
        - name: staging_area_id
          in: path
          description: A RFC4122-compliant ID for the staging area.
          required: true
          type: string
      responses:
        204:
          description: Staging area is now unlocked.
        default:
          description: Unexpected error

  /area/{staging_area_id}/{filename}:

    put:
      summary: Store a metadata file
      operationId: staging.api.area.put_file
      description: |
        Store a JSON metadata file in the staging area.
      parameters:
        - name: staging_area_id
          in: path
          description: A RFC4122-compliant ID for the staging area.
          required: true
          type: string
        - name: filename
          in: path
          description: Name of file to be placed in staging area.
          required: true
          type: string
        - name: body
          in: body
          schema:
            type: string
            format: binary
      responses:
        201:
          description: File was stored sucessfully.
        default:
          description: Unexpected error
