swagger: '2.0'
info:
  title: Staging API
  version: "0.0.2"
host: staging.dev.data.humancellatlas.org
schemes:
  - https
basePath: /v1
produces:
  - application/json
paths:
  /area/{staging_area_id}:
    post:
      summary: Create a Staging Area
      operationId: staging.api.area.create
      description: |
        Create a Staging Area
      parameters:
        - name: staging_area_id
          in: path
          description: |
            A RFC4122-compliant ID for the staging area.
          required: true
          type: string
          pattern: "[A-Za-z0-9]{8}-[A-Za-z0-9]{4}-[A-Za-z0-9]{4}-[A-Za-z0-9]{4}-[A-Za-z0-9]{12}"
        - name: cloud
          description: |
            Which cloud storage platform should be staging area be created in.
          in: query
          type: string
          enum: [aws, gcp]
          required: true
      responses:
        201:
          description: Staging area was created.
        409:
          description: A staging area with that ID already exists.
        default:
          description: Unexpected error
    delete:
      description: |
        Delete a Staging Area
      summary: Delete a Staging Area
      parameters:
        - name: staging_area_id
          in: path
          description: A RFC4122-compliant ID for the staging area.
          required: true
          type: string
        - name: cloud
          description: |
            Which cloud storage platform sthis staging area is in.
          in: query
          type: string
          enum: [aws, gcp]
          required: true
      responses:
        204:
          description: Staging area was deleted.
        404:
          description: Could not find a staging area with that ID.
        default:
          description: Unexpected error
  /area/{staging_area_id}/lock:
    post:
      summary: Lock a Staging Area
      operationId: staging.api.area.lock
      description: |
        Lock a Staging area so that submitters may not add/delete/rename files in it.
      parameters:
        - name: staging_area_id
          in: path
          description: A RFC4122-compliant ID for the staging area.
          required: true
          type: string
        - name: cloud
          description: |
            Which cloud storage platform sthis staging area is in.
          in: query
          type: string
          enum: [aws, gcp]
          required: true
      responses:
        204:
          description: Staging area is now locked.
    delete:
      summary: Unock a Staging Area
      operationId: staging.api.area.unlock
      description: |
        Unlock a Staging area so that submitters may add/delete/rename files in it.
      parameters:
        - name: staging_area_id
          in: path
          description: A RFC4122-compliant ID for the staging area.
          required: true
          type: string
        - name: cloud
          description: |
            Which cloud storage platform sthis staging area is in.
          in: query
          type: string
          enum: [aws, gcp]
          required: true
      responses:
        204:
          description: Staging area is now unlocked.
