swagger: '2.0'
info:
  title: Staging API
  version: "0.0.1"
host: hca-staging.czi.technology
schemes:
  - https
basePath: /v1
produces:
  - application/json
paths:
  /foo:
    get:
      description: |
        Hello
      summary: Hello
      responses:
        200:
          description: OK
        default:
          description: Unexpected error
